org.gradle.jvmargs=-Xmx6G

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=taniwha-remaked
mod_version=1.21.1-0.0.2
maven_group=eirmax

architectury_version=13.0.8
rei_version=16.0.799
jei_version=19.22.1.316

fabric_loader_version=0.16.10
fabric_api_version=0.116.6+1.21.1

neoforge_version=21.1.206

mod_menu_version=11.0.3